name: Rust CI

on:
  push:
    branches: [ main, develop ]   # ogni push su questi branch
  pull_request:
    branches: [ main, develop ]         # ogni PR diretta a develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Run cargo check
      run: cargo check

    - name: Run tests
      run: cargo test --all
