name: Cargo Build & Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Install rustfmt
        run: rustup component add rustfmt --toolchain ${{ matrix.toolchain }}
      - name: Check formatting
        run: cargo fmt --all -- --check
      - run: cargo build --verbose
      - run: cargo test --verbose
  

